mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.mybatisredis.entity
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/SYSDBA?charset=UTF-8&loginTimeout=30
    username: SYSDBA
    password: 123Dfh1999
    # 连接池配置（以默认的HikariCP为例）
    hikari:
      maximum-pool-size: 10  # 最大连接数
      minimum-idle: 5        # 最小空闲连接
      connection-timeout: 30000  # 连接超时时间（毫秒）
      idle-timeout: 600000    # 空闲连接超时时间（毫秒）


