mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.mybatisredis.entity
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/SYSDBA?charset=UTF-8&loginTimeout=30
    username: SYSDBA
    password: 123Dfh1999





